// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVCSCxI1XGI-PK3vLrAizW1PG5d6JWav0',
    appId: '1:197526864233:android:4b3a4bf6c190171a0b3df8',
    messagingSenderId: '197526864233',
    projectId: 'emergency-vehicle-assistance',
    storageBucket: 'emergency-vehicle-assistance.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6dS44VwdMG37jrsImoeQZgEvwSJ1GnSY',
    appId: '1:197526864233:ios:11c068865b96ada20b3df8',
    messagingSenderId: '197526864233',
    projectId: 'emergency-vehicle-assistance',
    storageBucket: 'emergency-vehicle-assistance.appspot.com',
    androidClientId: '197526864233-hrifacjusi9kt478s4buogpmp0fj6sim.apps.googleusercontent.com',
    iosClientId: '197526864233-de5jfplacn8degntf7e5risdud6la8qm.apps.googleusercontent.com',
    iosBundleId: 'com.example.vehicleAssistanceVendor',
  );
}
